### ISSUE TITLE
Difference between mapone and mapone-slim?

### ISSUE THREAD

**Issue by abhaybd** [k1tesurfen/mapome#1]
Btw, I love this project, it's just what I was looking for!

I can't really tell the difference between `mapone` and `mapone-slim`. They look very similar to me, so what are the differences between them?

**Comment by k1tesurfen** [comment]
Better late than never, but to answer your question: I had perfomance problems with the larger map. There were too many points on the paths I drew, which slowed my machine drastically. There is a option in Illustrator to remove those points on the paths while still trying to maintain the original shape of the path. So I adjusted the sliders so it looks pretty much the same but there are way less path points. Hope I could help

**Comment by abhaybd** [comment]
Thanks for getting back, that makes sense! I forget which one I ended up using, but I used this to laser engrave a map of middle earth for my wall. Thanks again for making this!
